apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mosquitto.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mosquitto.fullname" . }}-token-review
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mosquitto.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "mosquitto.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "mosquitto.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mosquitto.fullname" . }}-token-review
subjects:
- kind: ServiceAccount
  name: {{ include "mosquitto.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "mosquitto.fullname" . }}-token-review
  apiGroup: rbac.authorization.k8s.io
