apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
{{ .Values.service.annotations | toYaml | indent 4 }}
  {{- end }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ipFamilies: {{ .Values.service.ipFamilies | toJson }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
