name: Publish mosquitto-k8s container image
on:
  push:
    tags: [ "v*" ]
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  image-meta:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      tags: ${{ steps.docker-meta.outputs.tags }}
      labels: ${{ steps.docker-meta.outputs.labels }}
    steps:
      - id: docker-meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ghcr.io/matthiasvalvekens/mosquitto-k8s
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=ref,event=branch,enable=${{ !startsWith(github.ref, 'refs/tags/v') && github.ref != 'refs/heads/master' }}
            type=semver,pattern={{version}},event=tag
            type=semver,pattern={{major}}.{{minor}},event=tag
  run-build:
    runs-on: ubuntu-latest
    needs: [image-meta]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ needs.image-meta.outputs.tags }}
          labels: ${{ needs.image-meta.outputs.labels }}
          cache-to: type=gha,mode=max
          cache-from: type=gha
          platforms: linux/amd64,linux/arm64/v8
      - name: Sign images using GHA OIDC identity
        # this digest is for the manifest that combines all the platform images
        run: cosign sign --yes ghcr.io/matthiasvalvekens/mosquitto-k8s@${{ steps.build-push.outputs.digest }}
